global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'rabbitmq_idu_enricher'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.10.193.88:9418']

  - job_name: 'rabbitmq_idu_solrloader'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.10.193.88:9419']

  - job_name: 'sonar_db'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.10.193.93:9190']

  - job_name: 'sonar_idu'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.10.193.88:9180']

  - job_name: 'solrexporter_core'
    scrape_interval: 10s
    static_configs:
      - targets: ['solrexporter:8094']

  - job_name: 'solrexporter_jvm'
    scrape_interval: 10s
    static_configs:
      - targets: ['solrexporter:8095']

  - job_name: 'solrexporter_other'
    scrape_interval: 10s
    static_configs:
      - targets: ['solrexporter:8096']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']































































































































































