{
 "title": "Data Store Team Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Alerts list", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datalake Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bulks created",
     "type": "graph",
     "description": "Bulks that were saved to metadata table",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Created Bulks",
       "measurement": "Varonis Datalake Management.Bulks",
       "select": [
        [
         { "params": [ "Sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Saved" }
       ]
      }
     ]
    },
    {
     "title": "Bulks removed",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Bulks" }
     ],
     "targets": [
      {
       "alias": "Removed Bulks",
       "measurement": "Varonis Datalake Management.Bulks",
       "select": [
        [
         { "params": [ "Sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Removed" }
       ]
      }
     ]
    },
    {
     "title": "Replay Requests",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Request By" ], "type": "tag" },
        { "params": [ "Request Source" ], "type": "tag" },
        { "params": [ "Bulks Count" ], "type": "tag" },
        { "params": [ "TimeStamp" ], "type": "tag" }
       ],
       "measurement": "Varonis Datalake Management.Replay Requests",
       "select": [
        [
         { "params": [ "Count" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Bulks replayed",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Bulks" }
     ],
     "targets": [
      {
       "alias": "Replayed Bulks",
       "measurement": "Varonis Datalake Management.Bulks",
       "select": [
        [
         { "params": [ "Sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Replayed" }
       ]
      }
     ]
    },
    {
     "title": "Replay requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Bulks" }
     ],
     "targets": [
      {
       "alias": "Replay requests",
       "measurement": "Varonis Datalake Management.Replay Requests",
       "select": [
        [
         { "params": [ "Sum" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cifs Enricher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "Events Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Events Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CifsEnricher.EventsCount",
     "query": "SELECT mean(\"Sum\") FROM \"autogen\".\"CifsEnricher.EventsCount\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Events Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Events Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CifsEnricher.EventsLatency",
     "query": "SELECT mean(\"Max\") FROM \"autogen\".\"CifsEnricher.EventsLatency\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fetching Throughput",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Fetching Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CifsEnricher.FetchingThroughput",
     "query": "SELECT mean(\"Count\") FROM \"autogen\".\"CifsEnricher.FetchingThroughput\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Failures",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CifsEnricher.FailedEventsCount",
     "query": "SELECT mean(\"Count\") FROM \"autogen\".\"CifsEnricher.FailedEventsCount\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events written to DL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "measurement": "CifsEnricher.EventsCount",
     "query": "SELECT \"Sum\" FROM \"autogen\".\"CifsEnricher.EventsCount\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Sum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "EPS - write to DL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "measurement": "CifsEnricher.EventsCount",
     "query": "SELECT Sum(\"Sum\")/60 FROM \"autogen\".\"CifsEnricher.EventsCount\" WHERE $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "Sum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "measurement": "CifsEnricher.EventsLatency",
     "query": "SELECT \"Max\" FROM \"autogen\".\"CifsEnricher.EventsLatency\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB Fetching Throughput",
   "type": "graph",
   "description": "The number of elements we fetch from DB in a single fetch",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "EntityName" ], "type": "tag" }
     ],
     "measurement": "CifsEnricher.FetchingThroughput",
     "query": "SELECT \"Sum\" FROM \"CifsEnricher.ConcurrentDbFetchesPerEntity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB Fetching Time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "EntityName" ], "type": "tag" }
     ],
     "measurement": "CifsEnricher.FetchTime",
     "query": "SELECT \"Sum\" FROM \"CifsEnricher.ConcurrentDbFetchesPerEntity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Concurrent Fetching Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "EntityName" ], "type": "tag" }
     ],
     "measurement": "CifsEnricher.ConcurrentDbFetchesPerEntity",
     "query": "SELECT \"Sum\" FROM \"CifsEnricher.ConcurrentDbFetchesPerEntity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events Consumed (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "CifsEnricher.EventsConsumed",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cached/Uncached",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Cached",
     "measurement": "CifsEnricher.CacheHits",
     "query": "SELECT \"Sum\" FROM \"autogen\".\"CifsEnricher.CacheHits\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Uncached",
     "measurement": "CifsEnricher.CacheMiss",
     "query": "SELECT \"Sum\" FROM \"autogen\".\"CifsEnricher.CacheMiss\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Filtered Events",
   "type": "graph",
   "description": "Enhancing Filter - Filtered out count of enhancing filter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Filtered Events",
     "measurement": "CifsEnricher.FilteredEventsCount",
     "query": "SELECT \"Count\" FROM \"CifsEnricher.FilteredEventsCount\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process Message Failures",
   "type": "graph",
   "description": "Enhancing Translation - Number of failed translation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Failures",
     "measurement": "CifsEnricher.FailedEventsCount",
     "query": "SELECT \"Count\" FROM \"CifsEnricher.FailedEventsCount\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sql Extractor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Extractors Tasks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Number Of Extractors",
       "measurement": "Varonis Sql Extractor.Number Of Extractors",
       "select": [
        [
         { "params": [ "max" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Batch Duration In Seconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Batch Duration In Seconds",
       "measurement": "Varonis Sql Extractor.Batches Duration In Seconds",
       "select": [
        [
         { "params": [ "max" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Batches Created",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Batches Created",
       "measurement": "Varonis Sql Extractor.Batches",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Created" }
       ]
      }
     ]
    },
    {
     "title": "Batches Failed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Batches Failed",
       "measurement": "Varonis Sql Extractor.Batches",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Failed" }
       ]
      }
     ]
    },
    {
     "title": "Batches Retries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Batches Retries",
       "measurement": "Varonis Sql Extractor.Batches",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Retry" }
       ]
      }
     ]
    },
    {
     "title": "Extracted events count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Data Source Id $tag_DataSourceId",
       "groupBy": [
        { "params": [ "DataSourceId" ], "type": "tag" }
       ],
       "measurement": "Varonis Sql Extractor.Extractor Rows Count",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Solr Loader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average bulks loaded per second",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "measurement": "Varonis Solr Loader.Bulk",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Loaded" }
       ]
      }
     ]
    },
    {
     "title": "Average documents loaded per second",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "measurement": "Varonis Solr Loader.Document",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Loaded" }
       ]
      }
     ]
    },
    {
     "title": "Average documents read per second",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "measurement": "Varonis Solr Loader.Document",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Read" }
       ]
      }
     ]
    },
    {
     "title": "Bulks loaded",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Loaded bulks",
       "measurement": "Varonis Solr Loader.Bulk",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Operation", "operator": "=", "value": "Loaded" }
       ]
      }
     ]
    },
    {
     "title": "Bulks Processing time in seconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Seconds",
       "measurement": "Varonis Solr Loader.Bulk",
       "select": [
        [
         { "params": [ "max" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Operation", "operator": "=", "value": "ProcessingTimeInSeconds" }
       ]
      }
     ]
    },
    {
     "title": "Bulks failures",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Failed bulks",
       "measurement": "Varonis Solr Loader.Bulk",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Operation", "operator": "=", "value": "Failed" }
       ]
      }
     ]
    },
    {
     "title": "Writer tasks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Writer tasks",
       "measurement": "Varonis Solr Loader.Working tasks",
       "select": [
        [
         { "params": [ "max" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Type", "operator": "=", "value": "Writers" }
       ]
      }
     ]
    },
    {
     "title": "Documents read",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Number of docuemnts read",
       "measurement": "Varonis Solr Loader.Document",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Read" }
       ]
      }
     ]
    },
    {
     "title": "Documents Loaded to Solr",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Docs loaded",
       "measurement": "Varonis Solr Loader.Document",
       "query": "SELECT \"sum\" FROM \"Varonis Solr Loader.Document\" WHERE (\"Operation\" = 'Loaded') AND $timeFilter",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Loaded" }
       ]
      }
     ]
    },
    {
     "title": "Event age in minutes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Event age",
       "measurement": "Varonis Solr Loader.Event age",
       "select": [
        [
         { "params": [ "max" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Units", "operator": "=", "value": "Minutes" }
       ]
      }
     ]
    },
    {
     "title": "Events count per Json doc",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Events per Json",
       "measurement": "Varonis Solr Loader.Json Document",
       "select": [
        [
         { "params": [ "max" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Events count" }
       ]
      }
     ]
    },
    {
     "title": "Json docs created",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Json created",
       "measurement": "Varonis Solr Loader.Json Document",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Status", "operator": "=", "value": "Created" }
       ]
      }
     ]
    },
    {
     "title": "Bulk creator block -  Input queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Queue size",
       "measurement": "Varonis Solr Loader.Queue size",
       "select": [
        [
         { "params": [ "max" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Block", "operator": "=", "value": "Bulk creator" },
        { "condition": "AND", "key": "Input or output", "operator": "=", "value": "Input" }
       ]
      }
     ]
    },
    {
     "title": "Bulk creator block - Output queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Queue size",
       "measurement": "Varonis Solr Loader.Queue size",
       "select": [
        [
         { "params": [ "max" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Block", "operator": "=", "value": "Bulk creator" },
        { "condition": "AND", "key": "Input or output", "operator": "=", "value": "Output" }
       ]
      }
     ]
    },
    {
     "title": "Solr loader block - Input queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Queue size",
       "measurement": "Varonis Solr Loader.Queue size",
       "select": [
        [
         { "params": [ "max" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Block", "operator": "=", "value": "Solr loader" },
        { "condition": "AND", "key": "Input or output", "operator": "=", "value": "Input" }
       ]
      }
     ]
    },
    {
     "title": "Replay bulks progress",
     "type": "graph",
     "description": "Replay processes updates on percentage done",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Replay % ($tag_ReplayGuid)",
       "groupBy": [
        { "params": [ "ReplayGuid" ], "type": "tag" }
       ],
       "measurement": "Varonis Solr Loader.Replay Progress",
       "select": [
        [
         { "params": [ "Max" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Replay Updates",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Bulk Order" ], "type": "tag" },
        { "params": [ "ReplayGuid" ], "type": "tag" },
        { "params": [ "Bulk Order" ], "type": "tag" },
        { "params": [ "Total Replay Bulks Count" ], "type": "tag" }
       ],
       "measurement": "Varonis Solr Loader.Replay Progress",
       "select": [
        [
         { "params": [ "Max" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}