{
 "title": "Logs Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service Name",
    "query": {
     "query": "label_values({job=~\"[\\\\w]+\"},job)"
    }
   },
   { "name": "Search" }
  ]
 },
 "panels": [
  { "title": "Alerts status", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "Total Errors\\Warnings count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=~\"[\\\\w]+\"} |~\"WARN|ERROR\" [$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Errors\\Warnings count - Current time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=~\"[\\\\w]+\"} |~\"WARN|ERROR\" [$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "SolrLoader - Errors\\Warnings count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_over_time({job=\"solrloader\"} |~\"ERROR|WARN\" [1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "SqlExtractor - Errors\\Warnings count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_over_time({job=\"sqlextractor\"} |~\"ERROR|WARN\" [1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Enricher - Errors\\Warnings count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_over_time({job=\"enricher\"} |~\"ERROR|WARN\" [1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "CLM - Errors\\Warnings count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_over_time({job=\"CollectionManager\"} |~\"ERROR|WARN\" [1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "SolrMonitor - Errors\\Warning count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_over_time({job=\"SolrMonitor\"} |~\"ERROR|WARN\" [1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Solr - Errors\\Warnings count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_over_time({job=\"Solr\"} |~\"ERROR|WARN\" [1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Zookeeper WD - Errors\\Warnings count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_over_time({job=\"ZookeeperWatchdog\"} |~\"ERROR|WARN\" [1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Solr WD - Errors\\Warnings count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_over_time({job=\"SolrWatchdog\"} |~\"ERROR|WARN\" [1m])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Services logs - Warnings\\Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Warnings count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=~\"$job\"} |=\"WARN\" [1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Warnings logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=~\"$job\"} |=\"WARN\" |~ \"$Search\""
    }
   ]
  },
  {
   "title": "Errors count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=~\"$job\"} |~ `\\|ERROR\\|` [1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Errors logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "{job=~\"$job\"} |~ `\\|ERROR\\|` |~ \"$search\""
    },
    {
     "expr": "{job=~\"$job\"} |=\"ERROR\" |~ \"$Search\""
    }
   ]
  },
  {
   "title": "Services logs - All",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "All log levels -  INFO | WARN | ERROR ",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "{job=~\"$job\"} |~\"INFO|WARN|\" |~ \"$Search\""
      }
     ]
    }
   ]
  }
 ]
}