{
 "title": "Search Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "base_url",
    "query": {
     "query": "label_values(solr_ping{base_url=~\".+\"},base_url)"
    }
   },
   {
    "name": "core",
    "query": {
     "query": "label_values(solr_ping{base_url=~\"$base_url\"},core)"
    }
   },
   {
    "name": "idu_host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "time_filter_day_amount",
    "label": "Day amount",
    "query": "SHOW TAG VALUES WITH KEY = \"dayCount\""
   },
   {
    "name": "search_type",
    "label": "Search Type",
    "query": "SHOW TAG VALUES WITH KEY = \"type\""
   },
   {
    "name": "ScenarioType",
    "label": "ScenarioType",
    "query": "SHOW TAG VALUES WITH KEY = \"scenarioType\""
   },
   {
    "name": "RequestKind",
    "label": "Request Kind",
    "query": "SHOW TAG VALUES WITH KEY = \"requestKind\""
   },
   {
    "name": "SearchId",
    "label": "searchId",
    "query": "SHOW TAG VALUES WITH KEY = \"searchId\""
   }
  ]
 },
 "panels": [
  {
   "title": "First response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "$tag_type - $tag_dayCount",
     "groupBy": [
      { "params": [ "dayCount" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "SearchOperations",
     "select": [
      [
       { "params": [ "firstResponseTimeMs" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=~", "value": "/^$search_type$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$idu_host$/" },
      { "condition": "AND", "key": "successful", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "dayCount", "operator": "=~", "value": "/^$time_filter_day_amount$/" },
      { "condition": "AND", "key": "scenarioType", "operator": "=~", "value": "/^$ScenarioType$/" },
      { "condition": "AND", "key": "requestKind", "operator": "=~", "value": "/^$RequestKind$/" }
     ]
    }
   ]
  },
  {
   "title": "Complete response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "$tag_type - $tag_dayCount",
     "groupBy": [
      { "params": [ "dayCount" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "SearchOperations",
     "select": [
      [
       { "params": [ "completeResponseTimeMs" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=~", "value": "/^$search_type$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$idu_host$/" },
      { "condition": "AND", "key": "successful", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "dayCount", "operator": "=~", "value": "/^$time_filter_day_amount$/" },
      { "condition": "AND", "key": "scenarioType", "operator": "=~", "value": "/^$ScenarioType$/" },
      { "condition": "AND", "key": "requestKind", "operator": "=~", "value": "/^$RequestKind$/" }
     ]
    }
   ]
  },
  {
   "title": "Search Operations",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "scenarioType" ], "type": "tag" },
      { "params": [ "dayCount" ], "type": "tag" },
      { "params": [ "successful" ], "type": "tag" },
      { "params": [ "requestKind" ], "type": "tag" }
     ],
     "measurement": "SearchOperations",
     "select": [
      [
       { "params": [ "searchId" ], "type": "field" }
      ],
      [
       { "params": [ "completeResponseTimeMs" ], "type": "field" }
      ],
      [
       { "params": [ "firstResponseTimeMs" ], "type": "field" }
      ],
      [
       { "params": [ "resultCount" ], "type": "field" }
      ],
      [
       { "params": [ "errorMessage" ], "type": "field" }
      ],
      [
       { "params": [ "responseSizeInBytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$idu_host$/" },
      { "condition": "AND", "key": "dayCount", "operator": "=~", "value": "/^$time_filter_day_amount$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$search_type$/" },
      { "condition": "AND", "key": "scenarioType", "operator": "=~", "value": "/^$ScenarioType$/" },
      { "condition": "AND", "key": "requestKind", "operator": "=~", "value": "/^$RequestKind$/" }
     ]
    }
   ]
  },
  {
   "title": "Search times",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "dayCount" ], "type": "tag" }
     ],
     "measurement": "SearchOperations",
     "query": "SELECT percentile(\"completeResponseTimeMs\", 95) AS \"Complete 95th\", percentile(\"completeResponseTimeMs\", 50) AS \"C 50th\", median(\"completeResponseTimeMs\") AS \"C Median\", mean(\"completeResponseTimeMs\") AS \"C Mean\" FROM \"SearchOperations\" WHERE (\"host\" =~ /^$idu_host$/ AND \"type\" =~ /^$search_type$/ AND \"dayCount\" =~ /^$time_filter_day_amount$/ AND \"cached\" =~ /^$search_cached$/) AND $timeFilter GROUP BY \"type\", \"dayCount\", \"cached\"",
     "select": [
      [
       { "params": [ "completeResponseTimeMs" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "Complete 95th" ], "type": "alias" }
      ],
      [
       { "params": [ "completeResponseTimeMs" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "C 50th" ], "type": "alias" }
      ],
      [
       { "params": [ "completeResponseTimeMs" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "C Median" ], "type": "alias" }
      ],
      [
       { "params": [ "completeResponseTimeMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "C Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "firstResponseTimeMs" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "First 95th" ], "type": "alias" }
      ],
      [
       { "params": [ "firstResponseTimeMs" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ " F 50th" ], "type": "alias" }
      ],
      [
       { "params": [ "firstResponseTimeMs" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "F Median" ], "type": "alias" }
      ],
      [
       { "params": [ "firstResponseTimeMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "F Mean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$idu_host$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$search_type$/" },
      { "condition": "AND", "key": "dayCount", "operator": "=~", "value": "/^$time_filter_day_amount$/" },
      { "condition": "AND", "key": "scenarioType", "operator": "=~", "value": "/^$ScenarioType$/" },
      { "condition": "AND", "key": "requestKind", "operator": "=~", "value": "/^$RequestKind$/" }
     ]
    }
   ]
  },
  {
   "title": "Search times 95th percentile",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "dayCount" ], "type": "tag" }
     ],
     "measurement": "SearchOperations",
     "query": "SELECT  percentile(\"completeResponseTimeMs\", 95) AS \"Complete 95%\" FROM \"OperationCompleted\" WHERE $timeFilter GROUP BY \"type\"",
     "select": [
      [
       { "params": [ "completeResponseTimeMs" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "Complete" ], "type": "alias" }
      ],
      [
       { "params": [ "firstResponseTimeMs" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "First" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$idu_host$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$search_type$/" },
      { "condition": "AND", "key": "dayCount", "operator": "=~", "value": "/^$time_filter_day_amount$/" },
      { "condition": "AND", "key": "scenarioType", "operator": "=~", "value": "/^$ScenarioType$/" },
      { "condition": "AND", "key": "requestKind", "operator": "=~", "value": "/^$RequestKind$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_memory_bytes{base_url=~\"$base_url\", item=~\"freePhysicalMemorySize\"}",
     "legendFormat": "{{base_url}} - {{item}}"
    },
    {
     "expr": "solr_metrics_jvm_os_memory_bytes{base_url=~\"$base_url\", item=\"totalPhysicalMemorySize\"}",
     "legendFormat": "{{base_url}}- {{item}}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_heap_bytes{base_url=~\"$base_url\",item=\"committed\"}",
     "legendFormat": "{{base_url}} {{item}}"
    },
    {
     "expr": "solr_metrics_jvm_memory_heap_bytes{base_url=~\"$base_url\",item=\"used\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Solr Nodes - % CPU Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_cpu_load{base_url=~\"$base_url\", item=\"systemCpuLoad\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_pools_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{space}} {{item}}"
    }
   ]
  },
  {
   "title": "Total Full GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_gc_total{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Total Full GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_gc_seconds_total{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Total Search Cache Inserts Vs. Evictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (item) (solr_metrics_core_searcher_cache{type=\"filterCache\"})",
     "legendFormat": "filterCache -  {{item}}"
    },
    {
     "expr": "sum by (item) (solr_metrics_core_searcher_cache{type=\"queryResultCache\"})",
     "legendFormat": "queryResultCache {{item}}"
    }
   ]
  },
  {
   "title": "Searcher Cache - Avg. %Hit Ratio - Group by Type",
   "type": "graph",
   "description": "Ratio of cache hits to lookups for the current index searcher.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (type) (solr_metrics_core_searcher_cache_hitratio)",
     "legendFormat": "type={{type}}"
    },
    {
     "expr": "avg by (type,collection) (solr_metrics_core_searcher_cache_hitratio)",
     "legendFormat": "type={{type}} collection={{collection}}"
    }
   ]
  },
  {
   "title": "Search request count",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES EXACT CARDINALITY  from \"SearchOperations\"  WITH KEY = \"requestId\" WHERE scenarioType=~/$ScenarioType/ and dayCount=~/$time_filter_day_amount/ and  host=~/$idu_host/ group by \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solr - Living Cores (ping status)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(solr_ping{base_url=~\"$base_url\",core!=\"\"})",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Search Operation Error",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "scenarioType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "dayCount" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "SearchOperations",
     "select": [
      [
       { "params": [ "/^$SearchId$/" ], "type": "field" }
      ],
      [
       { "params": [ "completeResponseTimeMs" ], "type": "field" }
      ],
      [
       { "params": [ "firstResponseTimeMs" ], "type": "field" }
      ],
      [
       { "params": [ "responseSizeInBytes" ], "type": "field" }
      ],
      [
       { "params": [ "errorMessage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$idu_host$/" },
      { "condition": "AND", "key": "successful", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "scenarioType", "operator": "=~", "value": "/^$ScenarioType$/" }
     ]
    }
   ]
  },
  {
   "title": "Solr\\Loader docs rate (docs per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(solr_metrics_core_searcher_documents[5m]))",
     "legendFormat": " Solr Index Rate (docs per sec)"
    },
    {
     "expr": "win_perfmon_varonis_solr_loader_idu_documents_loaded_to_solr_rate_docs_per_sec",
     "legendFormat": "Loader doc Rate (docs per sec)"
    }
   ]
  },
  {
   "title": "Single Facets check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scenario requests by length of time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "< 1m $tag_scenarioId",
       "groupBy": [
        { "params": [ "requestId" ], "type": "tag" },
        { "params": [ "scenarioId" ], "type": "tag" }
       ],
       "measurement": "SearchOperations",
       "query": "SELECT count(completeResponseTimeMs) FROM \"SearchOperations\" WHERE (\"dayCount\" =~ /^$time_filter_day_amount$/ AND \"type\" =~ /^$search_type$/ AND \"host\" =~ /^$idu_host$/ AND \"scenarioId\" =~ /^$ScenarioId$/ AND completeResponseTimeMs < 60000) AND $timeFilter  group by scenarioId",
       "select": [
        [
         { "params": [ "completeResponseTimeMs" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "dayCount", "operator": "=~", "value": "/^$time_filter_day_amount$/" },
        { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$search_type$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$idu_host$/" },
        { "condition": "AND", "key": "scenarioId", "operator": "=~", "value": "/^$ScenarioId$/" }
       ]
      },
      {
       "alias": "2> x > 1m $tag_scenarioId",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(completeResponseTimeMs) FROM \"SearchOperations\" WHERE (\"dayCount\" =~ /^$time_filter_day_amount$/ AND \"type\" =~ /^$search_type$/ AND \"host\" =~ /^$idu_host$/ AND \"scenarioId\" =~ /^$ScenarioId$/ AND completeResponseTimeMs > 60000 AND completeResponseTimeMs < 120000) AND $timeFilter  group by scenarioId",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "> 2m  $tag_scenarioId",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(completeResponseTimeMs) FROM \"SearchOperations\" WHERE (\"dayCount\" =~ /^$time_filter_day_amount$/ AND \"type\" =~ /^$search_type$/ AND \"host\" =~ /^$idu_host$/ AND \"scenarioId\" =~ /^$ScenarioId$/ AND completeResponseTimeMs > 120000) AND $timeFilter  group by scenarioId",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Scenario requests by length of time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "< 1m $tag_scenarioId",
       "groupBy": [
        { "params": [ "requestId" ], "type": "tag" },
        { "params": [ "scenarioId" ], "type": "tag" }
       ],
       "measurement": "SearchOperations",
       "query": "SELECT count(completeResponseTimeMs) FROM \"SearchOperations\" WHERE (\"dayCount\" =~ /^$time_filter_day_amount$/ AND \"type\" =~ /^$search_type$/ AND \"host\" =~ /^$idu_host$/ AND \"scenarioId\" =~ /^$ScenarioId$/ AND completeResponseTimeMs < 60000) AND $timeFilter  group by scenarioId",
       "select": [
        [
         { "params": [ "completeResponseTimeMs" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "dayCount", "operator": "=~", "value": "/^$time_filter_day_amount$/" },
        { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$search_type$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$idu_host$/" },
        { "condition": "AND", "key": "scenarioId", "operator": "=~", "value": "/^$ScenarioId$/" }
       ]
      },
      {
       "alias": "2> x > 1m $tag_scenarioId",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(completeResponseTimeMs) FROM \"SearchOperations\" WHERE (\"dayCount\" =~ /^$time_filter_day_amount$/ AND \"type\" =~ /^$search_type$/ AND \"host\" =~ /^$idu_host$/ AND \"scenarioId\" =~ /^$ScenarioId$/ AND completeResponseTimeMs > 60000 AND completeResponseTimeMs < 120000) AND $timeFilter  group by scenarioId",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "> 2m  $tag_scenarioId",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(completeResponseTimeMs) FROM \"SearchOperations\" WHERE (\"dayCount\" =~ /^$time_filter_day_amount$/ AND \"type\" =~ /^$search_type$/ AND \"host\" =~ /^$idu_host$/ AND \"scenarioId\" =~ /^$ScenarioId$/ AND completeResponseTimeMs > 120000) AND $timeFilter  group by scenarioId",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Solr Nodes down (1=DOWN  ;  0=UP)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(grok_solrMonitorLog_solrNodeDown_total[5m])",
       "legendFormat": "{{SolrNode}}"
      }
     ]
    },
    {
     "title": "Request Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(solr_metrics_node_time_seconds_total{base_url=~\"$base_url\"})",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Solr Machines - % CPU Usage $base_url",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97 },
     "repeat": "base_url",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_cpu_load{base_url=~\"$base_url\"}",
       "legendFormat": "{{item}}"
      }
     ]
    },
    {
     "title": "Solr - down cores - doesn't work, down notes aren't reported",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "solr_ping{base_url=~\"$base_url\", core =~\"$core\",job=\"prom_to_zk1\"}"
      }
     ]
    }
   ]
  }
 ]
}