{
 "title": "Solr(Cores)",
 "description": "Solr Cores Dashboard Azure Dev Subscription 00002",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "zk_host",
    "query": "label_values(solr_ping{zk_host=~\".+\"},zk_host)"
   },
   {
    "name": "collection",
    "query": "label_values(solr_ping{zk_host=\"$zk_host\",collection=~\".+\"},collection)"
   },
   {
    "name": "shard",
    "query": "label_values(solr_collections_shard_state{zk_host=\"$zk_host\",collection=\"$collection\",shard=~\".+\"},shard)"
   },
   {
    "name": "replica",
    "query": "label_values(solr_collections_replica_state{zk_host=\"$zk_host\",collection=\"$collection\",shard=\"$shard\",replica=\".+\"},replica)"
   },
   {
    "name": "base_url",
    "query": "label_values(solr_ping{base_url=~\".+\"},base_url)"
   },
   {
    "name": "core",
    "query": "label_values(solr_ping{base_url=~\"$base_url\"},core)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Cores",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(solr_metrics_core_searcher_documents)"
    }
   ]
  },
  {
   "title": "Total cores size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"})"
    }
   ]
  },
  {
   "title": "Total documents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solr_metrics_core_searcher_documents)"
    }
   ]
  },
  {
   "title": "Document Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"}) / sum(solr_metrics_core_searcher_documents{base_url=~\"$base_url\"})"
    }
   ]
  },
  {
   "title": "Increase count - Update Requests (per node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(increase(solr_metrics_core_update_requests_total{base_url=~\"$base_url\"}[20m]) > 0, \"coreTimeSolt\", \"$1\", \"core\", \"Events_0_([0-9]{1,10}).*_[0-9].*_n1\")) by (base_url)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Total Soft commits (per node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(solr_metrics_core_update_handler_soft_auto_commits_executed_number > 0) by (base_url)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Total Hard commits (per node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(solr_metrics_core_update_handler_auto_commits_total > 0) by (base_url)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Collection\\Core Sizing Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents Per Day",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (day) ( label_replace(solr_metrics_core_searcher_documents{core=~\"$core\", item=\"numDocs\", category=\"SEARCHER\"}, \"day\", \"$month-$day\", \"core\", \"((Events_0_)(?P<year>[[:alnum:]]{2})(?P<month>[[:alnum:]]{2})(?P<day>[[:alnum:]]{2}))(.*replica_n1)\"))",
       "legendFormat": "{{day}}"
      }
     ]
    },
    {
     "title": "Total Collections count per day (in case single shared)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (day) ( label_replace(solr_metrics_core_searcher_documents{core=~\"$core\", item=\"numDocs\", category=\"SEARCHER\"}, \"day\", \"$month-$day\", \"collection\", \"((Events_0_)(?P<year>[[:alnum:]]{2})(?P<month>[[:alnum:]]{2})(?P<day>[[:alnum:]]{2}))(.*)\"))",
       "legendFormat": "{{day}}"
      }
     ]
    },
    {
     "title": "Documents per shared (top)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(800, solr_metrics_core_searcher_documents{item=\"numDocs\"})",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Size per shared (top)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(800, sum (solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"}) by (collection))",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Total Collections count per Solr node (single shard)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(solr_metrics_core_searcher_documents) by (base_url)",
       "legendFormat": "{{base_url}}"
      }
     ]
    },
    {
     "title": "Total documents count per Solr node (single shard)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(solr_metrics_core_searcher_documents) by (base_url)",
       "legendFormat": "{{base_url}}"
      }
     ]
    },
    {
     "title": "Avg. Collection  Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum by (collection) (solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"}))",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Avg. Core\\Index  Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(solr_metrics_core_index_size_bytes)",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Solr Cores - Ping Status (1=UP ; 0=DOWN)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk(30,solr_ping{base_url=~\"$base_url\",core!=\"\"})",
       "legendFormat": " {{base_url}}/{{core}}"
      }
     ]
    },
    {
     "title": "Avg. documents quantity per collection (in case single shared)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(solr_metrics_core_searcher_documents{core=~\"$core\", item=\"numDocs\"}) / count(solr_metrics_core_searcher_documents{core=~\"$core\", item=\"numDocs\"})",
       "legendFormat": "{{day}}"
      }
     ]
    }
   ]
  },
  { "title": "Core Index Update Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Soft commits (per node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(solr_metrics_core_update_handler_soft_auto_commits_executed_number > 0) by (base_url)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Optimize & Merge operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(solr_metrics_core_update_optimizes_total{base_url=~\"$base_url\"})",
     "legendFormat": "Optimizes"
    },
    {
     "expr": "topk(10,solr_metrics_core_update_optimizes_total{base_url=~\"$base_url\"})",
     "legendFormat": "Optimizes - {{core}}"
    },
    {
     "expr": "sum(solr_metrics_core_update_merges_total{base_url=~\"$base_url\", core!=\"\"})",
     "legendFormat": "Merges"
    },
    {
     "expr": "sum(solr_metrics_core_update_handler_merges_total{base_url=~\"$base_url\"})",
     "legendFormat": "Handler - Merges "
    },
    {
     "expr": "topk(10,solr_metrics_core_update_handler_merges_total{base_url=~\"$base_url\"})"
    }
   ]
  },
  {
   "title": "Index merges - Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(30, solr_metrics_core_update_merges_total{base_url=~\"$base_url\"})",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Optimize commands - Total",
   "type": "graph",
   "description": "Number of explicit optimize commands issued.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(30, solr_metrics_core_update_optimizes_total{base_url=~\"$base_url\"})",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "No. Col Indexed in last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(solr_metrics_core_update_handler_commits_total[1h]) > bool 1 )"
    }
   ]
  },
  {
   "title": "Collections indexed in the last hour",
   "type": "table",
   "description": "Need to upgrade to Grafana  5.2.2 and use $__range instead of hour for this table to by dynamic",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 37 },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_commits_total[15m])"
    }
   ]
  },
  {
   "title": "Core Update Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total update requests (per node)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(solr_metrics_core_update_requests_total{base_url=~\"$base_url\"} > 0) by (base_url)",
       "legendFormat": "{{base_url}}"
      }
     ]
    },
    {
     "title": "Update Requests increase (above X Avg.)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_core_update_requests_total{base_url=~\"$base_url\"}[10m]) > 100",
       "legendFormat": "{{base_url}}/{{core}}{{handler}}"
      }
     ]
    },
    {
     "title": "Update Request Time - 95th precentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_core_update_requestTimes_p95{base_url=~\"$base_url\"} > 500",
       "legendFormat": "{{base_url}}/{{core}}{{handler}}"
      }
     ]
    },
    {
     "title": "Update add\\Delete Actions errors messages - Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20, solr_metrics_core_update_error_messages_total{base_url=~\"$base_url\"})",
       "legendFormat": "{{base_url}}/{{core}}"
      }
     ]
    },
    {
     "title": "Update Errors - Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(30, solr_metrics_core_update_errors_total{base_url=~\"$base_url\"})",
       "legendFormat": "{{base_url}}/{{core}}{{handler}}"
      },
      {
       "expr": "topk(30, solr_metrics_core_update_low_errors_total{base_url=~\"$base_url\"})"
      }
     ]
    },
    {
     "title": "Update Timeouts - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(30, solr_metrics_core_update_timeouts_total{base_url=~\"$base_url\"})",
       "legendFormat": "{{base_url}}/{{core}}{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Search Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Searcher Cache - Hit Ratio",
     "type": "graph",
     "description": "Ratio of cache hits to lookups for the current index searcher.",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bottomk(2500,solr_metrics_core_searcher_cache_hitratio)",
       "legendFormat": "{{core}} {{type}} {{item}}"
      }
     ]
    },
    {
     "title": "Search Cache size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (solr_metrics_core_searcher_cache_size)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Searcher Cache - Avg. %Hit Ratio - Group by Type",
     "type": "graph",
     "description": "Ratio of cache hits to lookups for the current index searcher.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg by (type) (solr_metrics_core_searcher_cache_hitratio)",
       "legendFormat": "type={{type}}"
      }
     ]
    },
    {
     "title": "Total Search Cache Inserts Vs. Evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (item) (solr_metrics_core_searcher_cache{type=\"filterCache\"})",
       "legendFormat": "filterCache {{item}}"
      },
      {
       "expr": "sum by (item) (solr_metrics_core_searcher_cache{type=\"queryResultCache\"})",
       "legendFormat": "queryResultCache {{item}}"
      },
      {
       "expr": "sum by (item) (solr_metrics_core_searcher_cache{type=\"perSegFilter\"})",
       "legendFormat": "perSegFilter {{item}}"
      },
      {
       "expr": "sum by (item) (solr_metrics_core_searcher_cache{type=\"fieldValueCache\"})",
       "legendFormat": "fieldValueCache {{item}}"
      },
      {
       "expr": "sum by (item) (solr_metrics_core_searcher_cache{type=\"documentCache\"})",
       "legendFormat": "documentCache {{item}}"
      }
     ]
    },
    {
     "title": "Select Request Time - 95th precentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_core_select_requestTimes_p95{base_url=~\"$base_url\"} > 1000",
       "legendFormat": "{{base_url}}/{{core}}{{handler}}"
      }
     ]
    },
    {
     "title": "Query Errors - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(30, solr_metrics_core_query_errors_total{base_url=~\"$base_url\"})",
       "legendFormat": "{{base_url}}/{{core}}{{handler}}"
      }
     ]
    },
    {
     "title": "Query Timeouts - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(30, solr_metrics_core_query_timeouts_total{base_url=~\"$base_url\"})",
       "legendFormat": "{{base_url}}/{{core}}{{handler}}"
      }
     ]
    },
    {
     "title": "Pending Docs",
     "type": "graph",
     "description": "Number of documents which are pending commit",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(30, solr_metrics_core_update_handler_pending_docs{base_url=~\"$base_url\"})",
       "legendFormat": "{{base_url}}/{{core}}"
      }
     ]
    }
   ]
  }
 ]
}