{
 "title": "SQLExtractor & SolrLoader",
 "description": "SQLExtractor Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "content": "<center>-------</center>\n<h1><center>IDU</center></h1>\n<center>-------</center>"
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_computersystem_sonar_TotalPhysicalMemory"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_computersystem_sonar_NumberOfLogicalProcessors"
    }
   ]
  },
  {
   "title": "Avg. CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_processor_sonar_PercentProcessorTime{Name=\"_Total\"}"
    }
   ]
  },
  {
   "title": "Avg. Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(wmi_computersystem_sonar_TotalPhysicalMemory/1024/1024 - wmi_memory_sonar_AvailableMBytes)/(wmi_computersystem_sonar_TotalPhysicalMemory/1024/1024)*100"
    }
   ]
  },
  {
   "title": "Avg. Disk swap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "targets": [
    { "expr": "wmi_paging_sonar_PercentUsage" }
   ]
  },
  {
   "title": "Avg. Disk latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "perfmon_disk2_avg_disk_sec_read_TempDB_Partition",
     "legendFormat": "TempDB read"
    },
    {
     "expr": "perfmon_disk2_avg_disk_sec_Write_TempDB_Partition",
     "legendFormat": "TempDB write"
    },
    {
     "expr": "perfmon_disk3_avg_disk_sec_read_LogDB_Partition",
     "legendFormat": "LogDB read"
    },
    {
     "expr": "perfmon_disk3_avg_disk_sec_Write_LogDB_Partition",
     "legendFormat": "LogDB write"
    },
    {
     "expr": "perfmon_disk4_avg_disk_sec_read_DataDB_Partition",
     "legendFormat": "DataDB read"
    },
    {
     "expr": "perfmon_disk4_avg_disk_sec_Write_DataDB_Partition",
     "legendFormat": "DataDB write"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "content": "<center>-------</center>\n<h1><center>DB</center></h1>\n<center>-------</center>"
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_computersystem_db_TotalPhysicalMemory"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_computersystem_db_NumberOfLogicalProcessors"
    }
   ]
  },
  {
   "title": "Avg. CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_processor_db_PercentProcessorTime{Name=\"_Total\"}"
    }
   ]
  },
  {
   "title": "Avg. Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(wmi_computersystem_db_TotalPhysicalMemory/1024/1024 - wmi_memory_db_AvailableMBytes)/(wmi_computersystem_db_TotalPhysicalMemory/1024/1024)*100"
    }
   ]
  },
  {
   "title": "Avg. Disk swap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "targets": [
    { "expr": "wmi_paging_db_PercentUsage" }
   ]
  },
  {
   "title": "SQLExtractor & SolrLoader - Exective summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "content": "<br></br>\n<center>-----------------------</center>\n<h5><center>SQLExtractor</center></h5>\n<center>-----------------------</center>"
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Normalized  to real percent",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "perfmon_process_sqlextractor_precent_processor_time/(wmi_computersystem_sonar_NumberOfLogicalProcessors*100)*100",
     "legendFormat": "Extractor - % CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.SqlExtractor\"}",
     "legendFormat": "Extractor (Private Bytes)"
    }
   ]
  },
  {
   "title": "EPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_sqlextractor_batches_totaldoccount_metrics_TotalDocCount[5m])",
     "legendFormat": "Extractor - EPS"
    }
   ]
  },
  {
   "title": "Avg. Disk latency",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "perfmon_disk5_avg_disk_sec_read_DataLake_Partition",
     "legendFormat": "DataLake read"
    },
    {
     "expr": "perfmon_disk5_avg_disk_sec_Write_DataLake_Partition",
     "legendFormat": "DataLake write"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "content": "<br></br>\n<center>-----------------------</center>\n<h5><center>SolrLoader</center></h5>\n<center>-----------------------</center>"
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Normalized  to real percent",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "perfmon_process_solrloader_precent_processor_time/(wmi_computersystem_sonar_NumberOfLogicalProcessors*100)*100",
     "legendFormat": "Loader - % CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.SolrLoader.Service\"}",
     "legendFormat": "Loader (Private Bytes)"
    }
   ]
  },
  {
   "title": "EPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(solr_metrics_core_searcher_documents[5m]))",
     "legendFormat": "Solr - EPS"
    },
    {
     "expr": "win_perfmon_varonis_solr_loader_idu_documents_loaded_to_solr_rate_docs_per_sec",
     "legendFormat": "Loader - EPS"
    }
   ]
  },
  {
   "title": "Health - SqlExtractor & SolrLoader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "DBAdapter - events per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perfmon_varonis_DBAdapter_v3_eventsPerSec_consumed",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Shadow DB's - Events backlog",
   "type": "graph",
   "description": "Events exist in Shadow DB but not yet extracted to DataLake by SQLExtractor",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "db_shadowdb_backlog_missingevents_col2_MissigEvent_Backlog > 0",
     "legendFormat": "LH0836-SOLR1"
    },
    {
     "expr": "db_shadowdb_backlog_missingevents_col3_MissigEvent_Backlog > 0",
     "legendFormat": "LH0836-DV1"
    },
    {
     "expr": "db_shadowdb_backlog_missingevents_col4_MissigEvent_Backlog > 0",
     "legendFormat": "LH0836-SOLR2"
    },
    {
     "expr": "db_shadowdb_backlog_missingevents_col5_MissigEvent_Backlog > 0",
     "legendFormat": "LH0836-SOLR3"
    },
    {
     "expr": "db_shadowdb_backlog_missingevents_col6_MissigEvent_Backlog > 0",
     "legendFormat": "LH0836-ZKPR1"
    },
    {
     "expr": "db_shadowdb_backlog_missingevents_MissigEvent_Backlog > 0",
     "legendFormat": "LH0836-DB01"
    }
   ]
  },
  {
   "title": "SQLExtractor - events per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_sqlextractor_batches_totaldoccount_metrics_TotalDocCount[5m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "RabbitMQ - Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"vsb.topic=EventsDataLakeBulks;tag=SolrLoader Type=EventsBulkCreated\"}",
     "legendFormat": "SolrLoader - Total Created"
    },
    {
     "expr": "rabbitmq_queue_messages{queue=\"vsb.topic=SolrLoader;tag=SolrLoader Type=NewBulkToReadFromRetry\"}",
     "legendFormat": "SolrLoader - Total Retry"
    }
   ]
  },
  {
   "title": "SolrDataIndexer - events per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_solrdataindexer_batches_totaldoccount_metrics_TotalDocCount[5m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "SQLExtractor - Batch Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "db_spSqlextractor_BatchDurationStatistic_Batch_TimeDiffInMS > 0",
     "legendFormat": "{{BatchId}}"
    }
   ]
  },
  {
   "title": "SQLExtractor - Avg. Batches Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(db_spSqlextractor_BatchDurationStatistic_Batch_TimeDiffInMS> 1)",
     "legendFormat": "{{BatchId}}"
    }
   ]
  },
  {
   "title": "SQLExtractor - CSS  Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "db_spSqlextractor_BatchDurationStatistic_Sp_TimeDiffInMS > 0",
     "legendFormat": "{{BatchId}}"
    }
   ]
  },
  {
   "title": "SQLExtractor - Avg. Css Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(db_spSqlextractor_BatchDurationStatistic_Sp_TimeDiffInMS> 1)",
     "legendFormat": "{{BatchId}}"
    }
   ]
  },
  {
   "title": "Services UP status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "wmi_service_sonar_ProcessId{Name=\"Varonis.SqlExtractor.Service\"}",
     "legendFormat": "SqlExtractor"
    },
    {
     "expr": "wmi_service_sonar_ProcessId{Name=\"Varonis.DataLake.Management.Service\"}",
     "legendFormat": "DataLake"
    },
    {
     "expr": "wmi_service_sonar_ProcessId{Name=\"Varonis.SolrImporter.Service\"}",
     "legendFormat": "SolrImporter"
    },
    {
     "expr": "wmi_service_sonar_ProcessId{Name=\"Varonis.SolrLoader.Service\"}",
     "legendFormat": "SolrLoader"
    },
    {
     "expr": "wmi_service_sonar_ProcessId{Name=\"Varonis.Search.WebService\"}",
     "legendFormat": "Search"
    },
    {
     "expr": "wmi_service_sonar_ProcessId{Name=\"Varonis.AutoComplete.WebService\"}",
     "legendFormat": "AutoComplete"
    },
    {
     "expr": "wmi_service_sonar_ProcessId{Name=\"Varonis.DBAdapter.Consumer\"}",
     "legendFormat": "DBAdapterV3"
    }
   ]
  },
  {
   "title": "CSS Notifications table",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 41 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(db_notifications_metrics2_TimeDiffInMS) by (BatchStep)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{BatchStep}}",
     "measurement": "/^$core$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk % Free Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "wmi_disk_logical_sonar_PercentFreeSpace",
     "legendFormat": "IDU"
    },
    {
     "expr": "wmi_disk_logical_db_TempDB_PercentFreeSpace",
     "legendFormat": "TempDB"
    },
    {
     "expr": "wmi_disk_logical_db_DataDB_PercentFreeSpace",
     "legendFormat": "DataDB"
    },
    {
     "expr": "wmi_disk_logical_db_LogDB_PercentFreeSpace",
     "legendFormat": "LogDB"
    }
   ]
  },
  {
   "title": "IDU - Process (% CPU Time)",
   "type": "graph",
   "description": "Normalized  to real percent",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "perfmon_process_sqlextractor_precent_processor_time/(wmi_computersystem_sonar_NumberOfLogicalProcessors*100)*100",
     "legendFormat": "SQLExtractor"
    },
    {
     "expr": "perfmon_process_datalake_precent_processor_time/(wmi_computersystem_sonar_NumberOfLogicalProcessors*100)*100",
     "legendFormat": "DataLake "
    },
    {
     "expr": "perfmon_process_solrdataindexer_precent_processor_time/(wmi_computersystem_sonar_NumberOfLogicalProcessors*100)*100",
     "legendFormat": "DataIndexer "
    },
    {
     "expr": "perfmon_process_solrloader_precent_processor_time/(wmi_computersystem_sonar_NumberOfLogicalProcessors*100)*100",
     "legendFormat": "SolrLoader"
    }
   ]
  },
  {
   "title": "IDU - Process (Private Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.SqlExtractor\"}",
     "legendFormat": "SQLExtractor"
    },
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.DataLake.Management.Service\"}",
     "legendFormat": "DataLake"
    },
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.SolrDataIndexer.Service\"}",
     "legendFormat": "DataIndexer"
    },
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.SolrLoader.Service\"}",
     "legendFormat": "SolrLoader"
    }
   ]
  },
  {
   "title": "DB - Process (% CPU Time)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perfmon_process_sqlserver_precent_processor_time/100",
     "legendFormat": "SqlServer - used cores"
    },
    {
     "expr": "wmi_computersystem_db_NumberOfLogicalProcessors",
     "legendFormat": "SqlServer - Total cores"
    }
   ]
  },
  {
   "title": "DB - Process (memory used by SQLExtarctor)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "sum(db_dmv_top_queries_sqlextractor_memory_last_used_grant_kb)",
     "legendFormat": "used memory "
    },
    {
     "expr": "sum(db_dmv_top_queries_sqlextractor_memory_last_grant_kb)",
     "legendFormat": "Reserved memory"
    }
   ]
  },
  { "title": "Solr Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": ".NET Exceptions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perfmon_net_exceptions_sqlextractor_exceptions_total",
     "legendFormat": "sqlextractor_exceptions_total"
    },
    {
     "expr": "perfmon_net_exceptions_datalake_exceptions_total",
     "legendFormat": "datalake_exceptions_total"
    },
    {
     "expr": "perfmon_net_exceptions_solrdataindexer_exceptions_total",
     "legendFormat": "solrdataindexer_exceptions_total"
    },
    {
     "expr": "perfmon_net_exceptions_solrloader_exceptions_total",
     "legendFormat": "solrloader_exceptions_total"
    }
   ]
  },
  {
   "title": ".NET LocksAndThreads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perfmon_net_lockandthreads_sqlextractor_contention_rate_sec",
     "legendFormat": "sqlextractor_contention_rate_sec"
    },
    {
     "expr": "perfmon_net_lockandthreads_sqlextractor_current_queue_length",
     "legendFormat": "sqlextractor_current_queue_length"
    },
    {
     "expr": "perfmon_net_lockandthreads_sqlextractor_num_current_physical_threads",
     "legendFormat": "sqlextractor_num_current_threads"
    },
    {
     "expr": "perfmon_net_locksandthreads_datalake_contention_rate_sec",
     "legendFormat": "datalake_contention_rate_sec"
    },
    {
     "expr": "perfmon_net_locksandthreads_datalake_current_queue_length",
     "legendFormat": "datalake_current_queue_length"
    },
    {
     "expr": "perfmon_net_locksandthreads_datalake_num_current_physical_threads",
     "legendFormat": "datalake_num_current_threads"
    },
    {
     "expr": "perfmon_net_locksandthreads_solrdataindexer_contention_rate_sec",
     "legendFormat": "solrdataindexer_contention_rate_sec"
    },
    {
     "expr": "perfmon_net_locksandthreads_solrdataindexer_current_queue_length",
     "legendFormat": "solrdatainderxer_current_queue_length"
    },
    {
     "expr": "perfmon_net_locksandthreads_solrdataindexer_num_current_physical_threads",
     "legendFormat": "solrdataindexer_num_current_threads"
    },
    {
     "expr": "perfmon_net_lockandthreads_solrloader_contention_rate_sec",
     "legendFormat": "solrloader_contention_rate_sec"
    },
    {
     "expr": "perfmon_net_lockandthreads_solrloader_current_queue_length",
     "legendFormat": "solrloader_current_queue_length"
    },
    {
     "expr": "perfmon_net_lockandthreads_solrloader_num_current_physical_threads",
     "legendFormat": "solrloader_num_current_threads"
    }
   ]
  },
  {
   "title": ".NET Memory (GC)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perfmon_net_memory_sqlextractor_num_gen_0_collections",
     "legendFormat": "sqlextractor_num_gen_0_collections"
    },
    {
     "expr": "perfmon_net_memory_sqlextractor_num_gen_1_collections",
     "legendFormat": "sqlextractor_num_gen_1_collections"
    },
    {
     "expr": "perfmon_net_memory_sqlextractor_num_gen_2_collections",
     "legendFormat": "sqlextractor_num_gen_2_collections"
    },
    {
     "expr": "perfmon_net_memory_sqlextractor_precent_time_in_gc",
     "legendFormat": "sqlextractor_precent_time_in_gc"
    },
    {
     "expr": "perfmon_net_memory_datalake_precent_time_in_gc",
     "legendFormat": "datalake_precent_time_in_gc"
    },
    {
     "expr": "perfmon_net_memory_solrdataindexer_num_gen_0_collections",
     "legendFormat": "solrdataindexer_num_gen_0_collections"
    },
    {
     "expr": "perfmon_net_memory_solrdataindexer_num_gen_1_collections",
     "legendFormat": "solrdataindexer_num_gen_1_collections"
    },
    {
     "expr": "perfmon_net_memory_solrdataindexer_num_gen_2_collections",
     "legendFormat": "solrdataindexer_num_gen_2_collections"
    },
    {
     "expr": "perfmon_net_memory_solrloader_precent_time_in_gc",
     "legendFormat": "solrloader_precent_time_in_gc"
    },
    {
     "expr": "perfmon_net_memory_solrloader_num_gen_0_collections",
     "legendFormat": "solrloader - Gen 0"
    },
    {
     "expr": "perfmon_net_memory_solrloader_num_gen_1_collections",
     "legendFormat": "solrloader - Gen 1"
    },
    {
     "expr": "perfmon_net_memory_solrloader_num_gen_2_collections",
     "legendFormat": "solrloader - Gen 2"
    }
   ]
  },
  {
   "title": ".NET Memory - Heap size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "perfmon_net_memory_sqlextractor_num_bytes_in_all_heaps",
     "legendFormat": "sqlextractor - Heap Size"
    },
    {
     "expr": "perfmon_net_memory_solrloader_num_bytes_in_all_heaps",
     "legendFormat": "solrloader - Heap Size"
    }
   ]
  },
  {
   "title": ".NET Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perfmon_net_memory_sqlextractor_num_pinned_objects",
     "legendFormat": "sqlextractor_num_pinned_objects"
    },
    {
     "expr": "perfmon_net_memory_datalake_num_pinned_objects",
     "legendFormat": "datalake_num_pinned_objects"
    },
    {
     "expr": "perfmon_net_memory_solrdataindexer_num_pinned_objects",
     "legendFormat": "solrdataindexer_num_pinned_objects"
    }
   ]
  },
  {
   "title": "Process - Thread count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_process_sonar_ThreadCount{Name=\"Varonis.SqlExtractor\"}",
     "legendFormat": "SQLExtractor - Thread count"
    },
    {
     "expr": "wmi_process_sonar_ThreadCount{Name=\"Varonis.DataLake.Management.Service\"}",
     "legendFormat": "DataLake - Thread count"
    },
    {
     "expr": "wmi_process_sonar_ThreadCount{Name=\"Varonis.SolrDataIndexer.Service\"}",
     "legendFormat": "SolrDataIndexer - Thread count"
    },
    {
     "expr": "wmi_process_sonar_ThreadCount{Name=\"Varonis.SolrLoader.Service\"}",
     "legendFormat": "SolrLoader - Thread count"
    }
   ]
  },
  {
   "title": "Process - Handle count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_process_sonar_HandleCount{Name=\"Varonis.SqlExtractor\"}",
     "legendFormat": "SQLExtractor - Handle count"
    },
    {
     "expr": "wmi_process_sonar_HandleCount{Name=\"Varonis.DataLake.Management.Service\"}",
     "legendFormat": "DataLake - Handle count"
    },
    {
     "expr": "wmi_process_sonar_HandleCount{Name=\"Varonis.SolrDataIndexer.Service\"}",
     "legendFormat": "SolrDataIndexer - Handle count"
    },
    {
     "expr": "wmi_process_sonar_HandleCount{Name=\"Varonis.SolrLoader.Service\"}",
     "legendFormat": "SolrLoader - Handle count"
    }
   ]
  },
  {
   "title": "Process - Private Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.SqlExtractor\"}",
     "legendFormat": "SQLExtractor - Private Bytes"
    },
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.DataLake.Management.Service\"}",
     "legendFormat": "DataLake - Private Bytes"
    },
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.SolrDataIndexer.Service\"}",
     "legendFormat": "SolrDataIndexer - Private Bytes"
    },
    {
     "expr": "wmi_process_sonar_PrivateBytes{Name=\"Varonis.SolrLoader.Service\"}",
     "legendFormat": "SolrLoader - Private Bytes"
    }
   ]
  },
  {
   "title": "SolrDataIndexer - events per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_solrdataindexer_batches_totaldoccount_metrics_TotalDocCount[5m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Loader Service - Documents Loaded to Solr - total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_varonis_solr_loader_idu_documents_loaded_to_solr_total",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Loader Service - Documents Loaded to Solr - rate (docs per sec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_varonis_solr_loader_idu_documents_loaded_to_solr_rate_docs_per_sec",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Loader Service - Total Bulks Failures ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_varonis_solr_loader_idu_bulks_failures_total",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Loader Service - Event age in Minutes - Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_varonis_solr_loader_idu_event_age_in_minutes_avaerage",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "SQL  - Queries (SqlExtractor)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "CSS Notifications table",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "db_notifications_metrics2_TimeDiffInMS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$core$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DMVs - Top queries (by last execution time)",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "db_dmv_top_queries_n2_AvgElapsedTime"
      }
     ]
    },
    {
     "title": "SQLExtractor queries",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "db_dmv_top_queries_sqlextractor_n5_AvgElapsedTime"
      }
     ]
    },
    {
     "title": "SQLExtractor - Batch ID Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_sqlextractor_batches_metrics_TimeDiffInSec > 0",
       "legendFormat": "{{BatchId}}"
      }
     ]
    },
    {
     "title": "SQLExtractor - Batch ID DocCount",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "db_sqlextractor_batches_metrics_DocCount > 0",
       "legendFormat": "{{BatchId}}"
      }
     ]
    },
    {
     "title": "SQLEXtractor Batches Statistics",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "db_sqlextractor_batches_metrics_TimeDiffInSec"
      }
     ]
    },
    {
     "title": "Query Store - Top SQLExtractor queries (delay 30 min)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "db_querystore_queries_sqlextractor_Avg_Duration_ms"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock \\Timeout count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_locks_db_LockWaitsPersec",
       "legendFormat": "Lock Waits Per sec"
      },
      {
       "expr": "wmi_mssql_locks_db_LockTimeoutsPersec",
       "legendFormat": "Lock Timeouts Persec"
      },
      {
       "expr": "wmi_mssql_locks_db_NumberofDeadlocksPersec",
       "legendFormat": "Dead locks Per sec"
      },
      {
       "expr": "wmi_mssql_generalstatistics_db_Processesblocked",
       "legendFormat": "Processes blocked"
      }
     ]
    },
    {
     "title": "Lock Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_locks_db_AverageWaitTimems",
       "legendFormat": "Lock Waits Per sec"
      }
     ]
    },
    {
     "title": "Page life expectancy",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_buffermanager_db_Pagelifeexpectancy",
       "legendFormat": "Page life expectancy"
      }
     ]
    },
    {
     "title": "Memory Manager - Granted Workspace Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_memorymanager_db_GrantedWorkspaceMemoryKB",
       "legendFormat": "Granted Workspace Memory"
      }
     ]
    },
    {
     "title": "Latches",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_latches_db_AverageLatchWaitTimems",
       "legendFormat": "Average Latch Wait Timems"
      }
     ]
    },
    {
     "title": "Lazy writes Per sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_buffermanager_db_LazywritesPersec",
       "legendFormat": "Lazy writes Per sec"
      }
     ]
    },
    {
     "title": "Latch waits per sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_latches_db_LatchWaitsPersec",
       "legendFormat": "Latch Waits Per sec"
      }
     ]
    },
    {
     "title": "Longest Transaction Running Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 76 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_transactions_db_LongestTransactionRunningTime",
       "legendFormat": "Longest Transaction Running Time"
      }
     ]
    },
    {
     "title": "Wait Statistics - Lock waits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_waitstatistics_db_Lockwaits",
       "legendFormat": "Lock waits"
      },
      {
       "expr": "wmi_mssql_waitstatistics_db_Memorygrantqueuewaits",
       "legendFormat": "Memory grant queue waits"
      }
     ]
    },
    {
     "title": "Buffer cache hit ratio",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_buffermanager_db_Buffercachehitratio",
       "legendFormat": "Buffer cache hit ratio"
      }
     ]
    },
    {
     "title": "Workload Group Stats - CPU usage %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_workloadgroupstats_db_CPUusagePercent",
       "legendFormat": "CPU usage Percent"
      }
     ]
    }
   ]
  },
  {
   "title": "IDU HW & OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "IDU - % CPU Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "wmi_processor_sonar_PercentProcessorTime{Name=\"_Total\"}",
       "legendFormat": "% CPU Time"
      }
     ]
    },
    {
     "title": "SQLExtractor Process - % CPU Load  (Normalized  to real percent)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 98 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "perfmon_process_sqlextractor_precent_processor_time/(wmi_computersystem_sonar_NumberOfLogicalProcessors*100)*100",
       "legendFormat": "SQLExtractor - % Processor time"
      }
     ]
    },
    {
     "title": "IDU - Avg. % CPU Load",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 98 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "wmi_processor_sonar_PercentProcessorTime{Name=\"_Total\"}"
      }
     ]
    },
    {
     "title": "IDU - Context switches per sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_system_sonar_ContextSwitchesPersec",
       "legendFormat": "context switches sec"
      }
     ]
    },
    {
     "title": "IDU - Processor queue length",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_system_sonar_ProcessorQueueLength",
       "legendFormat": "Processor Queue Length"
      }
     ]
    },
    {
     "title": "IDU - Available Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "wmi_memory_sonar_AvailableMBytes",
       "legendFormat": "Available MBytes"
      }
     ]
    },
    {
     "title": "IDU - Paging - Percent usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 110 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "wmi_paging_sonar_PercentUsage", "legendFormat": "Paging percent usage" }
     ]
    },
    {
     "title": "IDU Disk % Free Space",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 110 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "wmi_disk_logical_sonar_PercentFreeSpace",
       "legendFormat": "Percent Free Space"
      }
     ]
    },
    {
     "title": "IDU Partition (=DataLake) Transfers/sec = IOPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "wmi_disk_logical_sonar_DiskTransfersPersec",
       "legendFormat": "IOPS"
      }
     ]
    },
    {
     "title": "IDU Partition (=DataLake) Bytes/sec = Throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 116 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "wmi_disk_logical_sonar_DiskBytesPersec",
       "legendFormat": "Throughput (Bytes/sec)"
      }
     ]
    },
    {
     "title": "IDU Partition (=DataLake)  Latency (ms)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 116 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "perfmon_disk5_avg_disk_sec_read_DataLake_Partition",
       "legendFormat": "read latency"
      },
      {
       "expr": "perfmon_disk5_avg_disk_sec_Write_DataLake_Partition",
       "legendFormat": "write latency"
      }
     ]
    },
    {
     "title": "Network - Output queue length",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_network_adapter_sonar_OutputQueueLength",
       "legendFormat": "Output queue length"
      }
     ]
    },
    {
     "title": "Network - Total Bytes vs. Bandwidth",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "wmi_network_adapter_sonar_BytesTotalPersec",
       "legendFormat": "Total Bytes per sec"
      },
      {
       "expr": "wmi_network_adapter_sonar_CurrentBandwidth/8",
       "legendFormat": "Current Bandwidth (Bytes)"
      }
     ]
    },
    {
     "title": "Network - Packets Errors\\Discarded",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 128 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_network_adapter_sonar_PacketsOutboundDiscarded",
       "legendFormat": "Packets outbound discarded"
      },
      {
       "expr": "wmi_network_adapter_sonar_PacketsOutboundErrors",
       "legendFormat": "Packets outbound errors"
      },
      {
       "expr": "wmi_network_adapter_sonar_PacketsReceivedDiscarded",
       "legendFormat": "Packets received discarded"
      },
      {
       "expr": "wmi_network_adapter_sonar_PacketsReceivedErrors",
       "legendFormat": "Packets received errors"
      }
     ]
    },
    {
     "title": "Network - Packets Received\\Sent per sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 128 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_network_adapter_sonar_PacketsReceivedPersec",
       "legendFormat": "Packets received per sec"
      },
      {
       "expr": "wmi_network_adapter_sonar_PacketsSentPersec",
       "legendFormat": "Packetssent per sec"
      }
     ]
    }
   ]
  },
  { "title": "DB HW & OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "% CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "wmi_processor_db_PercentProcessorTime{Name=\"_Total\"}",
     "legendFormat": "% CPU Time"
    }
   ]
  },
  {
   "title": "% CPU Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 99 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_processor_db_PercentProcessorTime{Name=\"_Total\"}"
    }
   ]
  },
  {
   "title": "Context switches per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_system_db_ContextSwitchesPersec",
     "legendFormat": "context switches sec"
    }
   ]
  },
  {
   "title": "Processor queue length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_system_db_ProcessorQueueLength",
     "legendFormat": "Processor Queue Length"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    { "expr": "wmi_memory_db_AvailableMBytes", "legendFormat": "Available MBytes" }
   ]
  },
  {
   "title": "Paging - Percent usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "wmi_paging_db_PercentUsage", "legendFormat": "Paging percent usage" }
   ]
  },
  {
   "title": "Disk % Free Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 111 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "wmi_disk_logical_sonar_PercentFreeSpace",
     "legendFormat": "IDU"
    },
    {
     "expr": "wmi_disk_logical_db_TempDB_PercentFreeSpace",
     "legendFormat": "TempDB"
    },
    {
     "expr": "wmi_disk_logical_db_DataDB_PercentFreeSpace",
     "legendFormat": "DataDB"
    },
    {
     "expr": "wmi_disk_logical_db_LogDB_PercentFreeSpace",
     "legendFormat": "LogDB"
    }
   ]
  },
  {
   "title": "TempDB partition - Transfers/sec = IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "wmi_disk_logical_db_TempDB_DiskTransfersPersec",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "TempDB Partition -  Throughput (=Bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 117 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "wmi_disk_logical_db_TempDB_DiskBytesPersec",
     "legendFormat": "Throughput (Bytes/sec)"
    }
   ]
  },
  {
   "title": "TempDB Partition - Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 117 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "perfmon_disk2_avg_disk_sec_read_TempDB_Partition",
     "legendFormat": "read latency"
    },
    {
     "expr": "perfmon_disk2_avg_disk_sec_Write_TempDB_Partition",
     "legendFormat": "write latency"
    }
   ]
  },
  {
   "title": "LogDB partition - Transfers/sec = IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "wmi_disk_logical_db_LogDB_DiskTransfersPersec",
     "legendFormat": "IOPS (C:)"
    }
   ]
  },
  {
   "title": "LogDB Partition -  Throughput (=Bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 123 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "wmi_disk_logical_db_LogDB_DiskBytesPersec",
     "legendFormat": "Throughput (Bytes/sec)"
    }
   ]
  },
  {
   "title": "LogDB Partition - Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 123 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "perfmon_disk3_avg_disk_sec_read_LogDB_Partition",
     "legendFormat": "write latency"
    },
    {
     "expr": "perfmon_disk3_avg_disk_sec_Write_LogDB_Partition",
     "legendFormat": "read latency"
    }
   ]
  },
  {
   "title": "DataDB partition - Transfers/sec = IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "wmi_disk_logical_db_DataDB_DiskTransfersPersec",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "DataDB Partition -  Throughput (=Bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 130 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "wmi_disk_logical_db_DataDB_DiskBytesPersec",
     "legendFormat": "Throughput (Bytes/sec)"
    }
   ]
  },
  {
   "title": "DataDB Partition - Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 130 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "perfmon_disk4_avg_disk_sec_read_DataDB_Partition",
     "legendFormat": "write latency"
    },
    {
     "expr": "perfmon_disk4_avg_disk_sec_Write_DataDB_Partition",
     "legendFormat": "read latency"
    }
   ]
  },
  {
   "title": "Network - Output queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_network_adapter_db_OutputQueueLength",
     "legendFormat": "Output queue length"
    }
   ]
  },
  {
   "title": "Network - Total Bytes vs. Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "wmi_network_adapter_db_BytesTotalPersec",
     "legendFormat": "Bytes Total per sec"
    },
    {
     "expr": "wmi_network_adapter_db_CurrentBandwidth/8",
     "legendFormat": "Current Bandwidth (Bytes)"
    }
   ]
  },
  {
   "title": "Network - Packets Errors\\Discarded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_network_adapter_db_PacketsOutboundDiscarded",
     "legendFormat": "Packets outbound discarded"
    },
    {
     "expr": "wmi_network_adapter_db_PacketsOutboundErrors",
     "legendFormat": "Packets outbound errors"
    },
    {
     "expr": "wmi_network_adapter_db_PacketsReceivedDiscarded",
     "legendFormat": "Packets received discarded"
    },
    {
     "expr": "wmi_network_adapter_db_PacketsReceivedErrors",
     "legendFormat": "Packets received errors"
    }
   ]
  },
  {
   "title": "Network - Packets Received\\Sent per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_network_adapter_db_PacketsReceivedPersec",
     "legendFormat": "Packets received per sec"
    },
    {
     "expr": "wmi_network_adapter_db_PacketsSentPersec",
     "legendFormat": "Packets sent per sec"
    }
   ]
  },
  {
   "title": "SQLExtractor & DataLake",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total batches\\created_files",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_sqlextractor_total_bataches",
       "legendFormat": "sqlextractor_total_bataches"
      },
      {
       "expr": "perfmon_varonis_sqlextractor_total_created_files",
       "legendFormat": "total_created_files"
      }
     ]
    },
    {
     "title": "Extraction rate - rows per sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_sqlextractor_rowsPerSec_readAndWrite_fromDBtoFile_by_single_extractor",
       "legendFormat": "rowsPerSec_fromDBtoFile_by_single_extractor"
      },
      {
       "expr": "perfmon_varonis_sqlextractor_rowsPerSec_readAndWrite_fromDBtoFile",
       "legendFormat": "rowsPerSec_fromDBtoFile"
      },
      {
       "expr": "perfmon_varonis_sqlextractor_rowsPerSec_readAndWrite_fromDBtoFile_fromTheProcessBeginning",
       "legendFormat": "rowsPerSec_fromDBtoFile_fromTheProcessBeginning"
      },
      {
       "expr": "perfmon_varonis_sqlextractor_rowsPerSec_readAndWrite_fromDBtoFile_lastHour",
       "legendFormat": "rowsPerSec_fromDBtoFile_lastHour"
      },
      {
       "expr": "perfmon_varonis_sqlextractor_rowsPerSec_read_fromDB_bySingleExtractor",
       "legendFormat": "rowsPerSec_read_fromDB_bySingleExtractor"
      }
     ]
    },
    {
     "title": "Total rows reads from DB to File",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_sqlextractor_total_rows_reads_from_db_to_files",
       "legendFormat": "total_rows_reads_from_db_to_files"
      }
     ]
    },
    {
     "title": "Total Failed Batches \\ Retries",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_sqlextractor_total_failed_batches",
       "legendFormat": "total_failed_batches"
      },
      {
       "expr": "perfmon_varonis_sqlextractor_total_retries",
       "legendFormat": "total_retries"
      }
     ]
    },
    {
     "title": "Parallel extractors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_sqlextractor_num_parallel_extractors",
       "legendFormat": "num_parallel_extractors"
      }
     ]
    },
    {
     "title": "Total Elapsed Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_sqlextractor_total_elapsed_time",
       "legendFormat": "total_elapsed_time"
      }
     ]
    },
    {
     "title": "Services UP status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(wmi_service_sonar_TagId{Name=\"Varonis.SqlExtractor.Service\", Status=\"OK\"})",
       "legendFormat": "SqlExtractor: \"OK\" Status"
      },
      {
       "expr": "count(wmi_service_sonar_TagId{Name=\"Varonis.DBAdapter\", Status=\"OK\"})",
       "legendFormat": "DBAdapter: \"OK\" Status"
      },
      {
       "expr": "count(wmi_service_sonar_TagId{Name=\"Varonis.DataLake.Management.Service\", Status=\"OK\"})",
       "legendFormat": "DataLake: \"OK\" Status"
      }
     ]
    }
   ]
  },
  {
   "title": "DBAdapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true,
   "panels": [
    {
     "title": "DBmanager tasks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_DBAdapter_dbmanager_current_pending_tasks",
       "legendFormat": "dbmanager_current_pending_tasks"
      },
      {
       "expr": "perfmon_varonis_DBAdapter_currentNumber_of_enqueued_dbmanager_tasks",
       "legendFormat": "currentNumber_of_enqueued_dbmanager_tasks"
      }
     ]
    },
    {
     "title": "Events consumed per sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_DBAdapter_eventsPerSec_consumed",
       "legendFormat": "events consumed per sec"
      }
     ]
    },
    {
     "title": "DB action time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_DBAdapter_perform_db_action_time",
       "legendFormat": "perform_db_action_time"
      }
     ]
    },
    {
     "title": "Total Acks sent",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_DBAdapter_total_acks_sent",
       "legendFormat": "total_acks_sent"
      }
     ]
    },
    {
     "title": "NAck sent per sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_DBAdapter_NAckPerSec_sent",
       "legendFormat": "NAckPerSec_sent"
      }
     ]
    },
    {
     "title": "Current bulks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_DBAdapter_currentNumber_of_bulks_collecting_events",
       "legendFormat": "currentNumber_of_bulks_collecting_events"
      }
     ]
    },
    {
     "title": ".NET exceptions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_net_exceptions_DBAdapter_exceptions_total",
       "legendFormat": "sqlextractor_exceptions_total"
      },
      {
       "expr": "perfmon_net_exceptions_DBAdapter_exceptions_per_sec",
       "legendFormat": "sqlextractor_exceptions_per_sec"
      }
     ]
    },
    {
     "title": ".NET Memory (GC)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_net_memory_DBAdapter_num_gen_0_collections",
       "legendFormat": "DBAdapter_num_gen_0_collections"
      },
      {
       "expr": "perfmon_net_memory_DBAdapter_num_gen_1_collections",
       "legendFormat": "DBAdapter_num_gen_1_collections"
      },
      {
       "expr": "perfmon_net_memory_DBAdapter_num_gen_2_collections",
       "legendFormat": "DBAdapter_num_gen_2_collections"
      },
      {
       "expr": "perfmon_net_memory_DBAdapter_precent_time_in_gc",
       "legendFormat": "DBAdapter_precent_time_in_gc"
      }
     ]
    },
    {
     "title": ".NET Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_net_memory_DBAdapter_large_object_heap_size",
       "legendFormat": "DBAdapter_large_object_heap_size"
      },
      {
       "expr": "perfmon_net_memory_DBAdapter_num_bytes_in_all_heaps",
       "legendFormat": "DBAdapter_num_bytes_in_all_heaps"
      },
      {
       "expr": "perfmon_net_memory_DBAdapter_num_pinned_objects",
       "legendFormat": "DBAdapter_num_pinned_objects"
      }
     ]
    },
    {
     "title": ".NET LocksAndThreads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_net_locksandthreads_DBAdapter_contention_rate_sec",
       "legendFormat": "DBAdapter_contention_rate_sec"
      },
      {
       "expr": "perfmon_net_locksandthreads_DBAdapter_current_queue_length",
       "legendFormat": "DBAdapter_current_queue_length"
      },
      {
       "expr": "perfmon_net_locksandthreads_DBAdapter_num_current_physical_threads",
       "legendFormat": "DBAdapter_num_current_threads"
      }
     ]
    },
    {
     "title": "Backup size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "perfmon_varonis_DBAdapter_size_of_backup",
       "legendFormat": "Backup size"
      }
     ]
    }
   ]
  },
  {
   "title": "Search Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "row - Initial Response Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_initime_avg_row_response > 0",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "row - total response time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_totaltime_avg_rows_response > 0 and win_perfmon_varonis_search_event_totaltime_avg_rows_response < 8000000",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "facet - Initial Response Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_initime_avg_facet_response > 0",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "facet - Total Response Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_totaltime_avg_facets_response > 0 and win_perfmon_varonis_search_event_totaltime_avg_facets_response < 18000000",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Solr Search - error Get Collection Details - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_errorGetCollectionDetails_total"
      }
     ]
    },
    {
     "title": "Solr Search - error Facet Run Query - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_errorFacetRunQuery_total"
      }
     ]
    },
    {
     "title": "Solr Search -  error Row Run Query - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_errorRowRunQuery_total"
      }
     ]
    },
    {
     "title": "Solr Search -  search Request - entity Event quantity - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_searchRequest_entityEvent_quantity_total"
      }
     ]
    },
    {
     "title": "Solr Search - Event - number of searches POST\\PUT",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_number_of_searches_postput"
      },
      {
       "expr": "win_perfmon_varonis_search_event_number_of_searches_postput"
      }
     ]
    },
    {
     "title": "Solr Search -  task entity Event - Average Runtime",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_task_entityEvent_averageRuntimeInMS"
      }
     ]
    },
    {
     "title": "Solr Search - snapshot Cache - last Time Accessed From Creation (MIN)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "m" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_snapshotCache_lastTimeAccessedFromCreation_inMinutes"
      }
     ]
    },
    {
     "title": "Solr Search - snapshot Cache - items In Cache",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_snapshotCache_itemsInCache"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Collections per search",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_collections_per_search"
      },
      {
       "expr": "win_perfmon_varonis_search_event_collections_per_search"
      }
     ]
    },
    {
     "title": "Solr Search - Event - concurrent tasks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_concurrent_taks"
      },
      {
       "expr": "win_perfmon_varonis_search_event_concurrent_taks"
      }
     ]
    },
    {
     "title": "Solr Search - Event - facet tasks per search",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_facet_tasks_per_search"
      },
      {
       "expr": "win_perfmon_varonis_search_event_facet_tasks_per_search"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Pending tasks search",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_pending_tasks_search"
      },
      {
       "expr": "win_perfmon_varonis_search_event_pending_tasks_search"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Terminated POST\\PUT requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_terminated_postput_requests"
      },
      {
       "expr": "win_perfmon_varonis_search_event_terminated_postput_requests"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Terminated POST search requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_terminated_post_search_requests"
      },
      {
       "expr": "win_perfmon_varonis_search_event_terminated_post_search_requests"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Avg. removed terminated facet tasks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_avg_removed_terminated_facet_tasks"
      },
      {
       "expr": "win_perfmon_varonis_search_event_avg_removed_terminated_facet_tasks"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Avg. removed terminated facet tasks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_avg_removed_terminated_facet_tasks"
      },
      {
       "expr": "win_perfmon_varonis_search_event_avg_removed_terminated_facet_tasks"
      }
     ]
    }
   ]
  }
 ]
}